
FROM node:12 AS ui-build
WORKDIR /spotifyClone/src/app
COPY client/ ./client/
RUN cd client && npm install && npm run build

FROM node:12 AS server-build
WORKDIR /root/
COPY --from=ui-build /spotifyClone/src/app/client/build ./client/build
COPY server/package*.json ./server/
RUN cd server && npm install
COPY server/ ./server/

EXPOSE 8080

CMD ["node", "./server/index.js"]

